### PR TITLE
added a new file named mathutils

### PR DESCRIPTION
**Pull request by dduvedi**
## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive `MathUtils` toolkit for various mathematical operations, including:
		- Basic arithmetic (addition, subtraction, multiplication, division)
		- Advanced functions (exponentiation, square root, factorial)
		- Array and list manipulations (sum, average, product)
		- Fibonacci number generation and GCD/LCM calculations
		- String concatenation and triplet counting in integer arrays

### CODE REVIEW

**Comment by dduvedi** [comment]
@CodiumAI-Agent /review

**Comment by dduvedi** [comment]
@CodiumAI-Agent /review

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by rajansh09** [comment]
Preparing review...

**Comment by rajansh08** [comment]
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>No key issues to review</strong></td></tr>
</table>

**Comment by rajansh09** [comment]
Preparing review...

**Comment by rajansh08** [comment]
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>No key issues to review</strong></td></tr>
</table>

**Comment by rajansh08** [comment]
## PR Code Suggestions ✨



<table><thead><tr><td>Category</td><td align=left>Suggestion&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td align=center>Score</td></tr><tbody><tr><td rowspan=4><strong>Enhancement</strong></td>
<td>



<details><summary>Use <code>Integer.sum()</code> method to calculate the sum of an array of integers</summary>

___


**Consider using <code>Integer.sum()</code> method to calculate the sum of an array of integers. It <br>is more concise and efficient.**

[app/src/main/java/Utility/MathUtils.java [31-36]](https://github.com/dduvedi/chatUsingFirebase/pull/1/files#diff-f9af77e42c112b453129ad4d2c15ef295270f167a72de8f773a751991b90b94fR31-R36)

```diff
-int sum = 0;
-for (Integer num : numbers) {
-    sum += num;
-}
+int sum = Integer.sum(numbers);
 
```                   
<details><summary>Suggestion importance[1-10]: 8</summary>

Why: The `Integer.sum()` method is more concise and efficient for calculating the sum of an array of integers.


</details></details></td><td align=center>8

</td></tr><tr><td>



<details><summary>Use <code>DoubleStream.sum()</code> method to calculate the sum of a list of numbers</summary>

___


**Consider using <code>DoubleStream.sum()</code> method to calculate the sum of a list of numbers. <br>It is more concise and efficient.**

[app/src/main/java/Utility/MathUtils.java [40-44]](https://github.com/dduvedi/chatUsingFirebase/pull/1/files#diff-f9af77e42c112b453129ad4d2c15ef295270f167a72de8f773a751991b90b94fR40-R44)

```diff
-double sum = 0.0;
-for (Object num : numbers) {
-    sum += ((Number) num).doubleValue();
-}
+double sum = numbers.stream().mapToDouble(num -> ((Number) num).doubleValue()).sum();
 
```                   
<details><summary>Suggestion importance[1-10]: 8</summary>

Why: The `DoubleStream.sum()` method is more concise and efficient for calculating the sum of a list of numbers.


</details></details></td><td align=center>8

</td></tr><tr><td>



<details><summary>Use <code>DoubleStream.reduce()</code> method to calculate the product of an array of numbers</summary>

___


**Consider using <code>DoubleStream.reduce()</code> method to calculate the product of an array of <br>numbers. It is more concise and efficient.**

[app/src/main/java/Utility/MathUtils.java [47-54]](https://github.com/dduvedi/chatUsingFirebase/pull/1/files#diff-f9af77e42c112b453129ad4d2c15ef295270f167a72de8f773a751991b90b94fR47-R54)

```diff
-double product = 1.0;
-for (Object num : numbers) {
-    // This can cause NullPointerException if any element is null
-    // and ClassCastException if any non-null element is not a Number
-    product *= ((Number) num).doubleValue();
-}
+double product = Arrays.stream(numbers).mapToDouble(num -> ((Number) num).doubleValue()).reduce(1.0, (a, b) -> a * b);
 
```                   
<details><summary>Suggestion importance[1-10]: 8</summary>

Why: The `DoubleStream.reduce()` method is more concise and efficient for calculating the product of an array of numbers.


</details></details></td><td align=center>8

</td></tr><tr><td>



<details><summary>Use <code>Math.pow()</code> method to calculate the power of a number</summary>

___


**Consider using <code>Math.pow()</code> method to calculate the power of a number. It is more <br>concise and efficient.**

[app/src/main/java/Utility/MathUtils.java [23-24]](https://github.com/dduvedi/chatUsingFirebase/pull/1/files#diff-f9af77e42c112b453129ad4d2c15ef295270f167a72de8f773a751991b90b94fR23-R24)

```diff
-return Math.pow(base, exponent);
+return base ** exponent;
 
```                   
<details><summary>Suggestion importance[1-10]: 7</summary>

Why: The `Math.pow()` method is more concise and efficient for calculating the power of a number.

</details></details></td><td align=center>7

</td></tr></tr></tbody></table>

**Comment by rajansh08** [comment]
Preparing PR description...

**Comment by rajansh09** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
### **Ask**❓


### **Answer:**
**Question 1: What is the purpose of the `MathUtils` class?**

**Answer:** The `MathUtils` class is a collection of utility methods that perform various mathematical operations. It includes methods for basic arithmetic (addition, subtraction, multiplication, division), advanced functions (exponentiation, square root, factorial), array and list manipulations (sum, average, product), Fibonacci number generation, GCD/LCM calculations, string concatenation, and counting triplets in integer arrays.

**Question 2: What are some of the potential issues with the `productOfArray` method?**

**Answer:** The `productOfArray` method calculates the product of all elements in an array. However, it assumes that all elements in the array are numbers. If any element is `null` or not a number, it will cause a `NullPointerException` or `ClassCastException`, respectively. To address this issue, you can add checks to ensure that all elements are numbers before performing the calculation.

**Question 3: How does the `fibonacci` method calculate Fibonacci numbers?**

**Answer:** The `fibonacci` method uses a recursive algorithm to calculate Fibonacci numbers. It takes a non-negative integer `n` as input and returns the nth Fibonacci number. The algorithm is based on the definition of Fibonacci numbers:

```
F(n) = F(n-1) + F(n-2)
```

where `F(0) = 0` and `F(1) = 1`.

**Question 4: What is the time complexity of the `countTriplets` method?**

**Answer:** The `countTriplets` method counts the number of triplets in an array whose sum is equal to a given value. It uses a brute-force approach by considering all possible combinations of three elements in the array. The time complexity of this method is O(n^3), where `n` is the length of the array.

**Question 5: Can you provide an example of how to use the `MathUtils` class?**

**Answer:** Here's an example of how you can use the `MathUtils` class in your code:

```java
import com.example.myapp.utils.MathUtils;

public class Main {

    public static void main(String[] args) {
        // Basic arithmetic operations
        int sum = MathUtils.add(10, 20);
        int difference = MathUtils.subtract(30, 15);
        int product = MathUtils.multiply(5, 6);
        double quotient = MathUtils.divide(100, 25);

        // Advanced functions
        double power = MathUtils.power(2, 3);
        double squareRoot = MathUtils.squareRoot(9);

        // Array and list manipulations
        int[] numbers = {1, 2, 3, 4, 5};
        int sumOfArray = MathUtils.sumArray(numbers);
        double averageOfList = MathUtils.averageOfList(Arrays.asList(1.0, 2.0, 3.0));
        double productOfArray = MathUtils.productOfArray(numbers);

        // Fibonacci number generation
        int fibonacciNumber = MathUtils.fibonacci(6);

        // GCD and LCM calculations
        int gcd = MathUtils.gcd(12, 18);
        int lcm = MathUtils.lcm(12, 18);

        // String concatenation
        String concatenatedString = MathUtils.concatenateStrings("Hello", "World");

        // Counting triplets
        int[] arr = {1, 5, 3, 2, 4};
        int tripletCount = MathUtils.countTriplets(arr);

        // Print the results
        System.out.println("Sum: " + sum);
        System.out.println("Difference: " + difference);
        System.out.println("Product: " + product);
        System.out.println("Quotient: " + quotient);
        System.out.println("Power: " + power);
        System.out.println("Square root: " + squareRoot);
        System.out.println("Sum of array: " + sumOfArray);
        System.out.println("Average of list: " + averageOfList);
        System.out.println("Product of array: " + productOfArray);
        System.out.println("Fibonacci number: " + fibonacciNumber);
        System.out.println("GCD: " + gcd);
        System.out.println("LCM: " + lcm);
        System.out.println("Concatenated string: " + concatenatedString);
        System.

**Comment by rajansh08** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
Preparing answer...

**Comment by rajansh08** [comment]
Preparing review...

**Comment by rajansh08** [comment]
Preparing review...

**Comment by dduvedi** [comment]
Preparing review...

**Comment by dduvedi** [comment]
**[Persistent review](https://github.com/dduvedi/chatUsingFirebase/pull/1#issuecomment-2390866723)** updated to latest commit https://github.com/dduvedi/chatUsingFirebase/commit/bd4017a8cfefe82c541d52d2c6225801afac44b0

**Pull request closed without merging**
